package Interfaces;

import gestionmediatheque.Operateur;
import java.awt.Color;
import java.awt.event.*;
// import java.beans.Statement;
import java.sql.*;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author NJElectro
 */
public class Login extends javax.swing.JFrame {
    /**
     * Creates new form Login
     */
    private void initialize() {
        jPanel1.requestFocusInWindow();
    }
    public Login() {
        initComponents();
         initialize();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN PAGE");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/57814.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 0, 44)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SE CONNECTER");

        username.setBackground(new java.awt.Color(235, 235, 255));
        username.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        username.setForeground(new java.awt.Color(102, 102, 102));
        username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username.setText("Username");
        username.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        Password.setBackground(new java.awt.Color(235, 235, 255));
        Password.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        Password.setForeground(new java.awt.Color(102, 102, 102));
        Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Password.setText("........");
        Password.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Login");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 57, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(username)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                            .addComponent(Password))
                        .addGap(107, 107, 107))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordFocusLost(evt);
            }
        });
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        jButton1.addActionListener(new ActionListener() {
        String usrnme = username.getText();
        char[] p = Password.getPassword();
        String passwd = new String(p);
//            @Override
//            public void actionPerformed(ActionEvent e) {
        try (Connection conn = Utilitaire.getConnection();) {

            PreparedStatement stmt1 = conn
                    .prepareStatement(
                            "SELECT * FROM employee WHERE cin = ? AND motdepasse = ?");
            PreparedStatement stmt2 = conn
                    .prepareStatement(
                            "SELECT * FROM usager WHERE cin = ? AND motdepasse = ?");
            stmt1.setString(1, usrnme);
            stmt1.setString(2, passwd);
            stmt2.setString(1, usrnme);
            stmt2.setString(2, passwd);
            ResultSet query1 = stmt1.executeQuery();
            ResultSet query2 = stmt2.executeQuery();

            if (query1.next()) {
                Operateur.getUsrId(query1.getLong(1));
                EspaceEmploye espace = new EspaceEmploye();
                espace.setVisible(true);
                Login.this.dispose();
            } else if (query2.next()) {
                Operateur.getUsrId(query2.getLong(1));
                EspaceUsager espace = new EspaceUsager();
                espace.setVisible(true);
                Login.this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "aucun copmte avec ces information",
                        "Information incorrecte", JOptionPane.ERROR_MESSAGE);
                username.setText("");
                Password.setText("");
                Login espace = new Login();
                espace.setVisible(true);
                Login.this.dispose();
            }
            query1.close();
            query2.close();
            // conn.close();
        } catch (SQLException e) {
            System.err.println("Database error: " + e.getMessage());
            // Display a more user-friendly error message
            JOptionPane.showMessageDialog(null, "Une erreur de connexion à la base de données est survenue. Veuillez réessayer plus tard.",
                    "Erreur", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            System.err.println("Unexpected error: " + ex.getMessage());
            JOptionPane.showMessageDialog(null, "Une erreur s'est produite. Veuillez réessayer plus tard.",
                    "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        // System.out.println(" " + usrnme + " " + passwd);
//            }
//        });
    }//GEN-LAST:event_jButton1ActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed
    private void usernameFocusLost(java.awt.event.FocusEvent evt) {
        // TODO add your handling code here:
        if (username.getText().equals("")) {
            username.setText("Username");
            username.setForeground(Color.BLACK);
        }
    }
    private void usernameFocusGained(java.awt.event.FocusEvent evt) {
        // TODO add your handling code here:
        if (username.getText().equals("Username")) {
            username.setText("");
            username.setForeground(Color.BLACK);
        }
    }
    private void PasswordFocusGained(java.awt.event.FocusEvent evt) {
        // TODO add your handling code here:
        char[] password = Password.getPassword();
        if (password.length > 0 && Arrays.equals(password, "........".toCharArray())) {
            Password.setText("");
            Password.setForeground(Color.BLACK);
        }
    }
    private void PasswordFocusLost(java.awt.event.FocusEvent evt) {
        // TODO add your handling code here:
        char[] password = Password.getPassword();
        if (password.length == 0) {
            Password.setText("........");
            Password.setForeground(Color.BLACK);
        }
    }
    public void init() {
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
