name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2
      
        - name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
            distribution: 'temurin' # ou 'zulu', 'adopt', selon votre préférence
            java-version: '11'      # ou la version de Java utilisée dans votre projet
      
        - name: Build with Ant
          run: ant -f build.xml

